gnodeb:
  controlif:
    ip: "192.168.121.50" # PacketRusher 所在機器IP位址
    port: 9487
  dataif:
    ip: "192.168.121.50" # PacketRusher 所在機器IP位址
    port: 2152
  plmnlist:
    mcc: "208"
    mnc: "93"
    tac: "000001"
    gnbid: "000008"
  slicesupportlist:
    sst: "01"
    sd: "000001" # optional, can be removed if not used
ue:
  msin: "0000000001"
  key: "8baf473f2f8fd09487cccbd7097c6862"
  opc: "8e27b6af0e692e750f32667a3b14605d"
  amf: "8000"
  sqn: "000000000023"
  dnn: "internet"
  routingindicator: "0000"
  hplmn:
    mcc: "208"
    mnc: "93"
  snssai:
    sst: 01
    sd: "010203" # optional, can be removed if not used
  integrity:
    nia0: false
    nia1: false
    nia2: true
    nia3: false
  ciphering:
    nea0: true
    nea1: false
    nea2: true
    nea3: false
amfif:
  - ip: "192.168.121.40" # AMF 所在處
    port: 38412
logs:
  level: 4
